### ISSUE TITLE
Allow CLI arguments to be configurable.

### ISSUE THREAD

**Issue by koaning** [koaning/skedulord#41]
This syntax would be nice; 

```yaml
user: vincent
schedule:
    - name: good-job
      command: python /Users/vincent/Development/skedulord/jobs/pyjob.py
      cron: "*/2 * * * *"
      arguments:
        org: rasahq
        repo: rasa
        output-dir: /home/vincent/Development/gh-dashb/issues
```
