### ISSUE TITLE
argparse doesn't play nice with skedulord

### ISSUE THREAD

**Issue by ieriii** [koaning/skedulord#47]
I have a question about argument parsing. 
Looking at the getting [started guide (schedule section)](https://koaning.github.io/skedulord/getting-started.html#schedule), I noted that you pass some custom arguments into the python script (i.e. --output and --repo). I double checked the source code, and my understanding `output` and `repo` are custom argument rather than default argument in skedulord like `retry` and `wait` - let me know if this is not correct. 

I tried to do the same with my own project but I'm currently getting an `unrecognized arguments` error.
Here a sample script to replicate the error:

```python
# test_lord.py
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--myarg1', help='arg1 name')
parser.add_argument('--myarg2', help='arg2 name')

args = parser.parse_args()

print(args.myarg1)
print(args.myarg2)
```

```yaml
# schedule.yml
user: user
schedule:
    - name: scraping-job
      command: python full/path/to/test_lord.py --myarg1 hello --myarg2 world
      retry: 1
      wait: 0
      cron: "*/1 * * * *"
```

Is the unrecognized arguments error expected or is there some other issues going on?

Thank you for your time. Appreciated.
And thank you very much for skedulord. I find it a really nice project.
